### ISSUE TITLE
add back updating problemsets daily once we can sync between gitlab and codeberg

### ISSUE THREAD

**Issue by bkf2020** [bkf2020/amcgen#4]
the code should match the other workflow.

but make sure to change the top part:
```yml
name: Update Problemsets Daily
on:
  schedule:
    - cron: '00 00 * * *'
```
